# Generated by Django 5.1.1 on 2024-09-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('nommbres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('dni', models.IntegerField(default=8)),
            ],
        ),
    ]
